booking/Controllers/HotelController.cs
using Domin.Entity;
using Infarstuructre.Domin;
using Infarstuructre.ViewModel;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;

namespace booking.Controllers
{
    public class HotelController : Controller
    {
        private readonly BookingDbContext _context;
        public HotelController(BookingDbContext context)
        {
            _context = context;
        }



        public async Task<IActionResult> Index()
        {
            List<HotelViewModel> hotelViewModelList = new List<HotelViewModel>();

            List<Hotel> hotelList = await _context.Hotels.Where(h=>h.IsDeleted == false).ToListAsync();

            foreach (var hotel in hotelList)
            {
                HotelViewModel hotelViewModel = new HotelViewModel
                {
                    hotel = hotel,
                    ImageFileName = hotel.HotelImage != null ? "hotelImage.jpg" : null 
                };

                hotelViewModelList.Add(hotelViewModel);
            }

            var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var requestCulture = requestCultureFeature?.RequestCulture;
            ViewBag.currentCulture = requestCulture.Culture.Name;

            return View(hotelViewModelList);
        }




        public async Task<IActionResult> Detail(int HotelId)
        {
            Hotel hotel=new Hotel();
            if (HotelId > 0)
            {
                hotel = await _context.Hotels.FirstOrDefaultAsync(h=>h.HotelId == HotelId);
                return View(hotel);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HotelViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Hotel hotel = new Hotel
                {
                    HotelNameFL = viewModel.hotel.HotelNameFL,
                    HotelNameSL = viewModel.hotel.HotelNameSL,
                    HotelRate = viewModel.hotel.HotelRate,
                    HotelLocation = viewModel.hotel.HotelLocation
                };

                if (viewModel.file != null && viewModel.file.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await viewModel.file.CopyToAsync(memoryStream);
                        hotel.HotelImage = memoryStream.ToArray();
                    }
                }

                _context.Add(hotel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        public IActionResult GetImage(int id)
        {
            var hotel = _context.Hotels.Find(id);
            if (hotel == null || hotel.HotelImage == null)
            {
                return NotFound();
            }

            return File(hotel.HotelImage, "image/jpeg");
        }
        public ActionResult Edit(int id)
        {
            // Retrieve the hotel by ID
            Hotel hotel = new Hotel(); 
            hotel = _context.Hotels.Find(id);
            if (hotel != null)
            {
                HotelViewModel hotelViewModel = new HotelViewModel
                {
                    hotel = hotel,
                    ImageFileName = hotel.HotelImage != null ? "hotelImage.jpg" : null
                };
                var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
                var requestCulture = requestCultureFeature?.RequestCulture;
                ViewBag.currentCulture = requestCulture.Culture.Name;
                return View(hotelViewModel);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditHotel(HotelViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Hotel existingHotel = await _context.Hotels.FindAsync(viewModel.hotel.HotelId);

                if (existingHotel == null)
                {
                    return NotFound();
                }

                existingHotel.HotelNameFL = viewModel.hotel.HotelNameFL;
                existingHotel.HotelNameSL = viewModel.hotel.HotelNameSL;
                existingHotel.HotelRate = viewModel.hotel.HotelRate;
                existingHotel.HotelLocation = viewModel.hotel.HotelLocation;

                if (viewModel.file != null && viewModel.file.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await viewModel.file.CopyToAsync(memoryStream);
                        existingHotel.HotelImage = memoryStream.ToArray();
                    }
                }

                _context.Update(existingHotel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            // Retrieve the hotel by ID
            Hotel hotel = await _context.Hotels.FindAsync(id);

            if (hotel == null)
            {
                return NotFound();
            }

            List<Package> packages = await _context.Packages
            .Where(p => p.HotelId == id)
            .ToListAsync();
            foreach (var package in packages)
            {
                package.IsDeleted = true;
            }
           
            hotel.IsDeleted = true;
            _context.Packages.UpdateRange(packages);
            _context.Hotels.Update(hotel);
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(Index));
        }

    }
}

booking/Controllers/ReservationsController.cs
using Domin.Entity;
using Infarstuructre.Domin;
using Infarstuructre.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Data;
using System.Security.Claims;
using System.IO;
using Microsoft.Extensions.Localization;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.Header;
using Microsoft.Data.SqlClient;
using Rotativa.AspNetCore;
using Infarstuructre.Helper;

namespace booking.Controllers
{
    public class ReservationsController : Controller
    {
        protected readonly BookingDbContext _context;
        private readonly IStringLocalizer<ReservationsController> _localizer;
        protected readonly IWebHostEnvironment _webHostEnvironment;
        public ReservationsController(BookingDbContext Context, IWebHostEnvironment webHostEnvironment, IStringLocalizer<ReservationsController> localizer)
        {
            _context = Context;
            _localizer = localizer;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index(Reservation reservationpag)
        {
            List<ReservationViewModel> viewModelList = new List<ReservationViewModel>();
            List<Reservation> reservations = new List<Reservation>();
            reservations = await _context.Reservations.Where(r=>r.IsDeleted == false).ToListAsync();
            foreach (var reservation in reservations)
            {
                Hotel hotel = await _context.Hotels.FindAsync(reservation.HotelId);
                Package package = await _context.Packages.FindAsync(reservation.PackageId);
                Customer customer = await _context.Customers.FindAsync(reservation.CustomerId);
                ReservationViewModel viewModel = new ReservationViewModel
                {
                    reservation = reservation,
                    hotel = hotel,
                    package = package,
                    customer = customer
                };
                viewModelList.Add(viewModel);
            }
            var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var requestCulture = requestCultureFeature?.RequestCulture;
            ViewBag.currentCulture = requestCulture.Culture.Name;

            ViewBag.Reservation = reservationpag;
            return View(viewModelList);
        }
        public async Task<IActionResult> test()
        {
           

            return View();
        }


        public async Task<IActionResult> Create(int hotelId,int packageId)
        {
            var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var requestCulture = requestCultureFeature?.RequestCulture;
            var hotels = _context.Hotels.Where(h => h.IsDeleted == false).ToList();
            var packages = _context.Packages.Where(p => p.IsDeleted == false).ToList();
            var customers = _context.Customers.Where(c => c.IsDeleted == false).ToList();

            if (requestCulture.Culture.Name == "en")
            {
                ViewBag.HotelList = new SelectList(hotels, "HotelId", "HotelNameSL");
            }
            else
            {
                ViewBag.HotelList = new SelectList(hotels, "HotelId", "HotelNameFL");
            }
            ViewBag.PackageList = new SelectList(packages, "PackageId", "PackageName");
            ViewBag.CustomerList = customers.ToList();
            ViewBag.packageId = packageId.ToString();
            ViewBag.hotelId = hotelId.ToString();

            return View();
        }
        [HttpGet]
        public IActionResult GetPackagesByHotelId(int hotelId)
        {
            var packages = new List<Package>();
            if (hotelId > 0)
            {
                packages = _context.Packages.Where(p => p.HotelId == hotelId).ToList();
            }
            else
            {
                packages = _context.Packages.Where(p => p.IsDeleted == false).ToList();
            }
            return Json(packages);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReservationViewModel viewModel)
        {
            string loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string loggedInUserName = User.FindFirstValue(ClaimTypes.Name);
            if (string.IsNullOrEmpty(loggedInUserId) || string.IsNullOrEmpty(loggedInUserName))
            {
                return RedirectToAction("Logout", "Accounts");
            }
            Reservation reservation = new Reservation
            {
                EmployeeId = loggedInUserId,
                HotelId = viewModel.reservation.HotelId,
                PackageId = viewModel.reservation.PackageId,
                CustomerId = viewModel.reservation.CustomerId,
                AdultNo = viewModel.reservation.AdultNo,
                KidNo = viewModel.reservation.KidNo,
                StartDate = viewModel.reservation.StartDate,
                EndDate = viewModel.reservation.EndDate,
                Residencylevel = viewModel.reservation.Residencylevel,
                Numberofextrachairs = viewModel.reservation.Numberofextrachairs,
                Amountofextrachairs = viewModel.reservation.Amountofextrachairs,
                ReservationDateTime = DateTime.Now,
                TotalPrice = viewModel.reservation.TotalPrice,
                Discount = viewModel.reservation.Discount,
                Paid = viewModel.reservation.Paid,
                Remain = viewModel.reservation.Remain,
                LastModify = DateTime.Now,
                UserName = loggedInUserName,
                IsDeleted = false,
                DeleteReason = ""
            };
            _context.Add(reservation);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult GetPackageData(int packageId)
        {
            return Json(_context.Packages.Find(packageId));
        }
        //public IActionResult Print()
        //{
        //    var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
        //    var requestCulture = requestCultureFeature?.RequestCulture;
        //    DataTable dataTable = new DataTable();
        //    using (var connection = new SqlConnection(_context.Database.GetDbConnection().ConnectionString))
        //    {
        //        using (var command = connection.CreateCommand())
        //        {
        //            command.CommandText = "PrintReservation";
        //            command.CommandType = CommandType.StoredProcedure;

        //            var param1 = new SqlParameter("@ReservationId", SqlDbType.Int);
        //            param1.Value = 7;
        //            command.Parameters.Add(param1);

        //            var param2 = new SqlParameter("@Lang", SqlDbType.NVarChar);
        //            param2.Value = requestCulture;
        //            command.Parameters.Add(param2);

        //            connection.Open();

        //            using (var reader = command.ExecuteReader())
        //            {
                        
        //                dataTable.Load(reader);
                       
        //            }
        //        }
        //    }

        //    LocalReport localReport = new LocalReport();
        //    localReport.ReportPath = Path.Combine(_webHostEnvironment.WebRootPath, "Reports", "Report.rdlc");

        //    var rds = new ReportDataSource();
        //    rds.Name = "DeviceSalesReport";
        //    rds.Value = dataTable;

        //    localReport.DataSources.Add(rds);

        //    string mimeType;
        //    string encoding;
        //    string filenameExtension;
        //    string[] streams;
        //    Warning[] warnings;

        //    byte[] renderedBytes = localReport.Render(
        //        "PDF", // PDF, Excel, Word, etc.
        //        null,
        //        out mimeType,
        //        out encoding,
        //        out filenameExtension,
        //        out streams,
        //        out warnings);
        //    return File(renderedBytes, mimeType);

        //}



        public async Task<IActionResult> Edit(int id)
        {
            Reservation reservation =await _context.Reservations.FindAsync(id);
            Hotel hotel = await _context.Hotels.FindAsync(reservation.HotelId);
            Customer customer = await _context.Customers.FindAsync(reservation.CustomerId);
            Package package = await _context.Packages.FindAsync(reservation.PackageId);
            ReservationViewModel model = new ReservationViewModel
            {
                reservation = reservation,
                hotel = hotel,
                customer = customer,
                package = package,
            };
            var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var requestCulture = requestCultureFeature?.RequestCulture;
            var hotels = _context.Hotels.Where(h => h.IsDeleted == false).ToList();
            var packages = _context.Packages.Where(p => p.IsDeleted == false).ToList();
            var customers = _context.Customers.Where(c => c.IsDeleted == false).ToList();

            if (requestCulture.Culture.Name == "en")
            {
                ViewBag.HotelList = new SelectList(hotels, "HotelId", "HotelNameSL");
            }
            else
            {
                ViewBag.HotelList = new SelectList(hotels, "HotelId", "HotelNameFL");
            }
            ViewBag.PackageList = new SelectList(packages, "PackageId", "PackageName");
            ViewBag.CustomerList = customers.ToList();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

booking/Views/HomePage/HomePage.cshtml
@model List<HomePageViewModel>
@{
    var customer = ViewBag.Customer as Customer;
}

<div class="card-header d-flex align-items-center justify-content-start m-3">
    <h3 class="card-title" style="margin-left:20px">@Localizer["lbHotelReservation"]</h3>


    <div class="card-tools ">
    </div>
</div>

<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var hotelViewModel in Model)
        {
            <input hidden="hidden" class="hotel-id" value="@hotelViewModel.Hotel.HotelId" />
            <div class="col">
                <div class="card">
                    @if (!string.IsNullOrEmpty(hotelViewModel.ImageFileName))
                    {
                        var imageSrc = Url.Action("GetImage", "Hotel", new { id = hotelViewModel.Hotel.HotelId });
                        <img src="@imageSrc" class="card-img-top" alt="Hotel Image" width="250" height="250" />
                    }
                    else
                    {
                        <span>No Photo Available</span>
                    }
                    <div class="card-body">
                        <h5 class="card-title">@hotelViewModel.Hotel.HotelNameFL</h5>
                        <p class="card-text">@hotelViewModel.Hotel.HotelLocation</p>
                        <p class="card-text text-warning">
                            @Localizer["lbRate"] : @hotelViewModel.Hotel.HotelRate
                            @for (int i = 0; i < hotelViewModel.Hotel.HotelRate; i++)
                            {
                                <svg width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                </svg>
                            }

                        </p>




                        <!-- Form for reservation -->
                        <form asp-action="Create" asp-controller="Reservations" method="get">
                            <div class="col">
                                <div class="col-14 mt-3">

                                    <div class="input-group mb-3">
                                        <input type="text" class="package-name form-control" disabled="disabled" aria-label="Text input with dropdown button">
                                        <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">@Localizer["lbpackages"]</button>
                                        <ul class="dropdown-menu">
                                            @foreach (var package in hotelViewModel.Packages)
                                            {
                                                <li><a class="dropdown-item" onclick="setPackageValue(this, '@package.PackageId', '@package.PackageName')">@package.PackageName</a></li>
                                            }
                                        </ul>
                                    </div>
                                </div>

                                <div class="col-6">
                                    <input name="packageId" class="package-id" type="hidden" />


                                    <input asp-for="@hotelViewModel.Hotel.HotelId" type="hidden" name="hotelId" />





                                    <button type="submit" class="btn btn-primary mt-3"> @Localizer["lbbtBookNow"] </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
</div>






@section Script
{
    @if (!string.IsNullOrEmpty(Context.Session.GetString("msgType")))
    {
        if (Context.Session.GetString("msgType") == "success")
        {
            <script>
                Swal.fire({
                    icon: "success",
                    title: ' @Context.Session.GetString("titel")',
                    text: '@Html.Raw(Context.Session.GetString("msg"))',
                    showConfirmButton: 'حسناً',
                });
            </script>
        }
        else
        {
            <script>
                Swal.fire({
                    icon: "error",
                    title: '@Context.Session.GetString("titel")',
                    text: '@Html.Raw(Context.Session.GetString("msg"))',
                    showConfirmButton: 'حسناً',


                });

            </script>
        }
        Context.Session.SetString("msgType", "");
    }


    <script src="~/js/homepage.js"></script>

}

<style>
    /* Style for the select element */
    .form-select {
        appearance: none; /* Remove default appearance */
        -webkit-appearance: none; /* For older versions of Chrome/Safari */
        -moz-appearance: none; /* For older versions of Firefox */
        background-color: #f5f5f5; /* Background color */
        border: 1px solid #ccc; /* Border */
        padding: 8px 12px; /* Padding */
        font-size: 16px; /* Font size */
        border-radius: 5px; /* Border radius */
        width: 200px; /* Width */
    }


        .form-select option {
            background-color: #f5f5f5; /* Background color */
            color: #333; /* Text color */
        }

</style>

<script src="~/js/homepage.js"></script>

<!-- Your select element -->