booking/Controllers/PackagesController.cs
using Domin.Entity;
using Infarstuructre.Domin;
using Infarstuructre.ViewModel;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;

namespace booking.Controllers
{
    public class PackagesController : Controller
    {
        private readonly BookingDbContext _context;
        public PackagesController(BookingDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<PackageViewModel> packageViewModelList = new List<PackageViewModel>();
            List<Package> packages = await _context.Packages.Where(p=>p.IsDeleted == false).ToListAsync();

            foreach (var package in packages)
            {
                Hotel hotel = await _context.Hotels.FirstOrDefaultAsync(h => h.HotelId == package.HotelId);

                PackageViewModel packageViewModel = new PackageViewModel
                {
                    Package = package,
                    Hotel = hotel
                };

                packageViewModelList.Add(packageViewModel);
            }
            var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var requestCulture = requestCultureFeature?.RequestCulture;
            ViewBag.currentCulture = requestCulture.Culture.Name;

            return View(packageViewModelList);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var requestCulture = requestCultureFeature?.RequestCulture;
            var hotels = _context.Hotels.Where(h => h.IsDeleted == false).ToList(); // Fetch the list of hotels from the database
            if (requestCulture.Culture.Name == "en")
            {
                ViewBag.HotelList = new SelectList(hotels, "HotelId", "HotelNameSL");
            }
            else
            {
                ViewBag.HotelList = new SelectList(hotels, "HotelId", "HotelNameFL");
            }
            return View(new PackageViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PackageViewModel model)
        {
            if (ModelState.IsValid)
            {
                var package = new Package
                {
                    PackageName = model.Package.PackageName,
                    //StartDate = model.Package.StartDate,
                    //EndDate = model.Package.EndDate,
                    AdultPrice = model.Package.AdultPrice,
                    KidPrice = model.Package.KidPrice,
                    HotelId = model.Package.HotelId
                };

                _context.Packages.Add(package);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }
        public IActionResult Edit(int Id)
        {

            PackageViewModel package = new PackageViewModel();
            package.Package = _context.Packages.Find(Id);
            if (package != null)
            {
                var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
                var requestCulture = requestCultureFeature?.RequestCulture;
                var hotels = _context.Hotels.Where(h => h.IsDeleted == false).ToList(); // Fetch the list of hotels from the database
                if (requestCulture.Culture.Name == "en")
                {
                    ViewBag.HotelList = new SelectList(hotels, "HotelId", "HotelNameSL");
                }
                else
                {
                    ViewBag.HotelList = new SelectList(hotels, "HotelId", "HotelNameFL");
                }
                return View(package);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PackageViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the existing package from the database
                var package = await _context.Packages.FindAsync(model.Package.PackageId);

                if (package == null)
                {
                    return NotFound(); // Or handle the case where the package is not found
                }

                // Update the properties of the existing package
                package.PackageName = model.Package.PackageName;
                //package.StartDate = model.Package.StartDate;
                //package.EndDate = model.Package.EndDate;
                package.AdultPrice = model.Package.AdultPrice;
                package.KidPrice = model.Package.KidPrice;
                package.HotelId = model.Package.HotelId;

                // Update the package in the context
                _context.Update(package);

                // Save changes to the database
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            // Retrieve the hotel by ID
            Package package = await _context.Packages.FindAsync(id);

            if (package == null)
            {
                return NotFound();
            }
            package.IsDeleted = true;
            _context.Packages.Update(package);
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(Index));
        }
    }
}

booking/Views/Packages/Create.cshtml
@model PackageViewModel
@{
    ViewData["Title"] = "Create Package";

    var hotelList = ViewBag.HotelList as SelectList;
}

<h2>@Localizer["lbbtCreateNewPackage"]</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Package.PackageName">@Localizer["lbPackageName"]</label>
        <input asp-for="Package.PackageName" class="form-control" />
        <span asp-validation-for="Package.PackageName" class="text-danger"></span>
    </div>
@* 
    <div class="form-group">
        <label asp-for="Package.StartDate">@Localizer["lbStartDate"]</label>
        <input asp-for="Package.StartDate" class="form-control" type="date" />
        <span asp-validation-for="Package.StartDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Package.EndDate">@Localizer["lbEndDate"]</label>
        <input asp-for="Package.EndDate" class="form-control" type="date" />
        <span asp-validation-for="Package.EndDate" class="text-danger"></span>
    </div> *@

    <div class="form-group">
        <label asp-for="Package.AdultPrice">@Localizer["lbAdultPrice"]</label>
        <input asp-for="Package.AdultPrice" class="form-control" />
        <span asp-validation-for="Package.AdultPrice" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Package.KidPrice">@Localizer["lbKidPrice"]</label>
        <input asp-for="Package.KidPrice" class="form-control" />
        <span asp-validation-for="Package.KidPrice" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Package.HotelId">@Localizer["lbHotelName"]</label>
        <select asp-for="Package.HotelId" class="form-control">
            @foreach (var hotel in hotelList)
            {
                <option value="@hotel.Value">@hotel.Text</option>
            }
        </select>
        <span asp-validation-for="Package.HotelId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="@Localizer["lbCreate"]" class="btn btn-primary" />
    </div>
</form>

booking/Views/Packages/Edit.cshtml
@model PackageViewModel
@{
    ViewData["Title"] = "Edit Package";

    var hotelList = ViewBag.HotelList as SelectList;
}

<h2>@Localizer["lbEdit"]</h2>

<form asp-action="Edit">
    <input type="hidden" asp-for="Package.PackageId" />
    <div class="form-group">
        <label asp-for="Package.PackageName">@Localizer["lbPackageName"]</label>
        <input asp-for="Package.PackageName" class="form-control" />
        <span asp-validation-for="Package.PackageName" class="text-danger"></span>
    </div>

@*     <div class="form-group">
        <label asp-for="Package.StartDate">@Localizer["lbStartDate"]</label>
        <input asp-for="Package.StartDate" class="form-control" type="date" />
        <span asp-validation-for="Package.StartDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Package.EndDate">@Localizer["lbEndDate"]</label>
        <input asp-for="Package.EndDate" class="form-control" type="date" />
        <span asp-validation-for="Package.EndDate" class="text-danger"></span>
    </div> *@

    <div class="form-group">
        <label asp-for="Package.AdultPrice">@Localizer["lbAdultPrice"]</label>
        <input asp-for="Package.AdultPrice" class="form-control" type="number" />
        <span asp-validation-for="Package.AdultPrice" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Package.KidPrice">@Localizer["lbKidPrice"]</label>
        <input asp-for="Package.KidPrice" class="form-control" type="number"  />
        <span asp-validation-for="Package.KidPrice" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Package.HotelId">@Localizer["lbHotelName"]</label>
        <select asp-for="Package.HotelId" class="form-control">
            @foreach (var hotel in hotelList)
            {
                <option value="@hotel.Value">@hotel.Text</option>
            }
        </select>
        <span asp-validation-for="Package.HotelId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="@Localizer["lbEdit"]" class="btn btn-primary" />
    </div>
</form>

booking/Views/Packages/Index.cshtml
@model List<PackageViewModel>
@{
    ViewData["Title"] = "Package";
    var currentCulture = ViewBag.currentCulture;
}


<div class="wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">@Localizer["lbCurrentPackage"]</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/Home/Index">@Localizer["lbHomePage"]</a></li>
                        <li class="breadcrumb-item active">@Localizer["lbMangePackage"]</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center justify-content-start">
                        <h3 class="card-title" style="margin-left:20px">@Localizer["lbCurrentPackage"]</h3>
                        <div class="row">
                            <div class="col-md-12">
                                <a href="@Url.Action("Create", "Packages")" class="btn btn-success">@Localizer["lbbtCreateNewPackage"]</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="tableRole" class="table table-bordered table-hover dataTable no-footer">
                            <thead>
                                <tr>
                                    <th>@Localizer["lbPackageName"]</th>
@*                                     <th>@Localizer["lbStartDate"]</th>
                                    <th>@Localizer["lbEndDate"]</th> *@
                                    <th>@Localizer["lbAdultPrice"]</th>
                                    <th>@Localizer["lbKidPrice"]</th>
                                    <th>@Localizer["lbHotelName"]</th>
                                    <th>@Localizer["lbHotelLocation"]</th>
                                    <th>@Localizer["lbPackageAction"]</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var packageViewModel in Model)
                                {
                                    <tr>
                                        <td>@packageViewModel.Package.PackageName</td>
@*                                         <td>@packageViewModel.Package.StartDate.ToString("yyyy-MM-dd")</td>
                                        <td>@packageViewModel.Package.EndDate.ToString("yyyy-MM-dd")</td> *@
                                        <td>@packageViewModel.Package.AdultPrice</td>
                                        <td>@packageViewModel.Package.KidPrice</td>
                                        <td>
                                            @if (currentCulture == "ar")
                                            {
                                                @packageViewModel.Hotel?.HotelNameFL
                                            }
                                            else
                                            {
                                                @packageViewModel.Hotel?.HotelNameSL
                                            }
                                        </td>
                                        <td>@(packageViewModel.Hotel?.HotelLocation)</td>
                                        <td>
                                            <!-- Edit button -->
                                            <div class="btn-group" role="group" aria-label="Actions">
                                                <a href="@Url.Action("Edit", "Packages", new { id = packageViewModel.Package.PackageId })" class="btn btn-info btn-sm mr-2">@Localizer["lbbtnEdit"]</a>
                                                <form id="deleteForm-@packageViewModel.Package.PackageId" asp-action="Delete" asp-controller="Packages" method="post">
                                                    <input type="hidden" name="id" value="@packageViewModel.Package.PackageId" />
                                                    <button type="button" class="btn btn-danger btn-sm" onclick="confirmDeletePackage('@packageViewModel.Package.PackageId')">@Localizer["lbbtnDelete"]</button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
    <script>
        function confirmDeletePackage(PackageId) {
            Swal.fire({
                title: '@Localizer["lbAreyousure"]',
                text: "@Localizer["lbCanback"]",
                icon: 'warning',
                showCancelButton: true,
                cancelButtonText: '@Localizer["lbcancelButtonText"]',
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: '@Localizer["lbYesdelete"]'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If confirmed, submit the form
                    document.getElementById('deleteForm-' + PackageId).submit();
                }
            });
        }
    </script>